import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;



public class DashboardPenyewa extends javax.swing.JFrame {
 
   
    /**
     * Creates new form DashboardPenyewa
     */
    public DashboardPenyewa() {
        initComponents();
        setLocationRelativeTo(null); // Center the window
        setTitle("Dashboard Penyewa - KosanKu");
        loadDataKamar();
    }

    /**
     * Method untuk memuat data kamar penyewa dari database
     */
    private void loadDataKamar() {
        if (!UserSession.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, "Sesi tidak valid, silakan login kembali.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Set nama penyewa
        jLabelNama.setText("Halo, " + UserSession.getCurrentUserName() + "!");

        try (Connection conn = DatabaseConnection.getConnection()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this,
                    "Koneksi database gagal!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            String query = """
                SELECT k.no_kamar, k.lantai, k.ukuran_kamar, k.fasilitas,
                       ks.tanggal_mulai, ks.status_sewa, ks.tenggat_pembayaran,
                       ks.status_kontrak
                FROM kontrak_sewa ks
                JOIN kamar k ON ks.id_kamar = k.id_kamar
                WHERE ks.id_penyewa = ? AND ks.status_kontrak = 'aktif'
                """;

            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, UserSession.getCurrentUserId());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Set data kamar ke label
                jNoKamarPenyewa.setText(rs.getString("no_kamar"));
                jLabelLantaiKamarPenyewa.setText("Lantai " + rs.getInt("lantai"));
                jLabelUkuranKamarPenyewa.setText(rs.getString("ukuran_kamar"));
                jLabelFasilitasKamarPenyewa.setText(rs.getString("fasilitas"));

                // Format tanggal
                SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
                Date tanggalMulai = rs.getDate("tanggal_mulai");
                if (tanggalMulai != null) {
                    jLabelTanggalMulaiPenyewa.setText(sdf.format(tanggalMulai));
                }

                Date tenggatPembayaran = rs.getDate("tenggat_pembayaran");
                if (tenggatPembayaran != null) {
                    jLabelTenggatPenyewa.setText(sdf.format(tenggatPembayaran));
                }

                // Status sewa
                String statusSewa = rs.getString("status_sewa");
                if ("perbulan".equalsIgnoreCase(statusSewa)) {
                    jLabelStatusPenyewa.setText("Sewa Per Bulan");
                } else if ("pertahun".equalsIgnoreCase(statusSewa)) {
                    jLabelStatusPenyewa.setText("Sewa Per Tahun");
                } else {
                    jLabelStatusPenyewa.setText(statusSewa);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data kamar aktif yang ditemukan untuk Anda.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                // Kosongkan label jika tidak ada data
                jNoKamarPenyewa.setText("-");
                jLabelLantaiKamarPenyewa.setText("-");
                jLabelUkuranKamarPenyewa.setText("-");
                jLabelFasilitasKamarPenyewa.setText("-");
                jLabelTanggalMulaiPenyewa.setText("-");
                jLabelTenggatPenyewa.setText("-");
                jLabelStatusPenyewa.setText("-");
            }
            
            rs.close();
            pst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error memuat data kamar: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonKamarku = new javax.swing.JButton();
        jButtonPembayaran = new javax.swing.JButton();
        jButtonPelaporan = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelTenggatPenyewa = new javax.swing.JLabel();
        jNoKamarPenyewa = new javax.swing.JLabel();
        jLabelLantaiKamarPenyewa = new javax.swing.JLabel();
        jLabelUkuranKamarPenyewa = new javax.swing.JLabel();
        jLabelFasilitasKamarPenyewa = new javax.swing.JLabel();
        jLabelTanggalMulaiPenyewa = new javax.swing.JLabel();
        jLabelStatusPenyewa = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("KOSANKU");

        jButtonKamarku.setText("Kamarku");
        jButtonKamarku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKamarkuMouseClicked(evt);
            }
        });

        jButtonPembayaran.setText("Pembayaran");
        jButtonPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPembayaranMouseClicked(evt);
            }
        });
        jButtonPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPembayaranActionPerformed(evt);
            }
        });

        jButtonPelaporan.setText("Pelaporan");
        jButtonPelaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPelaporanMouseClicked(evt);
            }
        });
        jButtonPelaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPelaporanActionPerformed(evt);
            }
        });

        jButtonLogout.setText("Logout");
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonKamarku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPelaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jButtonKamarku)
                .addGap(18, 18, 18)
                .addComponent(jButtonPembayaran)
                .addGap(18, 18, 18)
                .addComponent(jButtonPelaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 480));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Informasi Kamarku");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 19, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("No Kamar                                                :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 74, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Lantai                                                      :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 108, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ukuran Kamar                                         :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 148, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Fasilitas                                                   :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 188, 255, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tanggal Mulai Sewa                                 :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 228, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Status Sewa                                             :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 268, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tenggat Pembayaran Selanjutnya            :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 308, -1, -1));

        jLabelTenggatPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTenggatPenyewa.setText("Tanggal");
        jPanel1.add(jLabelTenggatPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 250, 20));

        jNoKamarPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNoKamarPenyewa.setText("No Kamar");
        jPanel1.add(jNoKamarPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 250, 30));

        jLabelLantaiKamarPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLantaiKamarPenyewa.setText("Lantai");
        jPanel1.add(jLabelLantaiKamarPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 250, 20));

        jLabelUkuranKamarPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUkuranKamarPenyewa.setText("Ukuran Kamar");
        jPanel1.add(jLabelUkuranKamarPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 240, 20));

        jLabelFasilitasKamarPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFasilitasKamarPenyewa.setText("Fasilitas");
        jPanel1.add(jLabelFasilitasKamarPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 250, 20));

        jLabelTanggalMulaiPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTanggalMulaiPenyewa.setText("Tanggal");
        jPanel1.add(jLabelTanggalMulaiPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 250, 20));

        jLabelStatusPenyewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelStatusPenyewa.setText("Status");
        jPanel1.add(jLabelStatusPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 250, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 590, 360));

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNama.setText("Halo, Nama!");
        getContentPane().add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\CIRA\\CODING\\LATIHAN\\Semester 4\\PBO\\PenyewaKosanKu\\src\\Assets\\white bg.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPembayaranActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButtonPembayaranActionPerformed

    private void jButtonPelaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPelaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPelaporanActionPerformed

    private void jButtonKamarkuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKamarkuMouseClicked
        // TODO add your handling code here:
         // Refresh informasi kamar
        loadDataKamar();
        JOptionPane.showMessageDialog(this, "Informasi kamar telah diperbarui!");

    }//GEN-LAST:event_jButtonKamarkuMouseClicked

    private void jButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            UserSession.clearSession(); // Hapus sesi
            new LoginPenyewa().setVisible(true); // Buka form login
            this.dispose(); // Tutup dashboard
        }
        
    }//GEN-LAST:event_jButtonLogoutMouseClicked

    private void jButtonPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPembayaranMouseClicked
        // TODO add your handling code here:
       new PembayaranPenyewa(UserSession.getCurrentUserId(), UserSession.getCurrentUserName()).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonPembayaranMouseClicked

    private void jButtonPelaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPelaporanMouseClicked
        // TODO add your handling code here:
         new PelaporanPenyewa(UserSession.getCurrentUserId(), UserSession.getCurrentUserName()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPelaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPenyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKamarku;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPelaporan;
    private javax.swing.JButton jButtonPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFasilitasKamarPenyewa;
    private javax.swing.JLabel jLabelLantaiKamarPenyewa;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelStatusPenyewa;
    private javax.swing.JLabel jLabelTanggalMulaiPenyewa;
    private javax.swing.JLabel jLabelTenggatPenyewa;
    private javax.swing.JLabel jLabelUkuranKamarPenyewa;
    private javax.swing.JLabel jNoKamarPenyewa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
