import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

public class RiwayatLaporanPenyewa extends javax.swing.JFrame {

private int idPenyewa;
    private String namaPenyewa;

    private RiwayatLaporanPenyewa() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public RiwayatLaporanPenyewa(int idPenyewa, String namaPenyewa) {
        this.idPenyewa = idPenyewa;
        this.namaPenyewa = namaPenyewa;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Riwayat Laporan - KosanKu");
        jLabel3.setText("Riwayat Laporan - " + namaPenyewa);
        setupTable();
        loadRiwayatLaporan(); // Load data automatically
    }

    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tanggal Laporan");
        model.addColumn("Deskripsi Masalah");
        model.addColumn("Status");
        model.addColumn("Tanggapan Pemilik");

        jTable1.setModel(model);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(180);
    }

    private void loadRiwayatLaporan() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear table

        String sql = """
            SELECT lk.tanggal_laporan, lk.deskripsi_masalah, lk.status_laporan,
                   lk.tanggapan_pemilik, lk.tanggal_tanggapan
            FROM laporan_kerusakan lk
            JOIN kontrak_sewa ks ON lk.id_kontrak = ks.id_kontrak
            WHERE ks.id_penyewa = ?
            ORDER BY lk.tanggal_laporan DESC
        """;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, idPenyewa);
            ResultSet rs = stmt.executeQuery();
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

            while (rs.next()) {
                Date tanggalLaporan = rs.getDate("tanggal_laporan");
                String deskripsiMasalah = rs.getString("deskripsi_masalah");
                String statusLaporan = rs.getString("status_laporan");
                String tanggapanPemilik = rs.getString("tanggapan_pemilik");

                String statusDisplay;
                switch (statusLaporan) {
                    case "pending":
                        statusDisplay = "Menunggu";
                        break;
                    case "dalam_penanganan":
                        statusDisplay = "Ditangani";
                        break;
                    case "selesai":
                        statusDisplay = "Selesai";
                        break;
                    default:
                        statusDisplay = statusLaporan;
                }

                if (tanggapanPemilik == null || tanggapanPemilik.trim().isEmpty()) {
                    tanggapanPemilik = "Belum ada tanggapan";
                }

                model.addRow(new Object[]{
                    sdf.format(tanggalLaporan),
                    deskripsiMasalah,
                    statusDisplay,
                    tanggapanPemilik
                });
            }

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                    "Belum ada riwayat laporan.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error: Gagal memuat riwayat laporan\n" + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonKamarku = new javax.swing.JButton();
        jButtonPembayaran = new javax.swing.JButton();
        jButtonPelaporan = new javax.swing.JButton();
        jButtonLogout1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonKembaliPelaporan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(150, 480));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("KOSANKU");

        jButtonKamarku.setText("Kamarku");
        jButtonKamarku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKamarkuMouseClicked(evt);
            }
        });

        jButtonPembayaran.setText("Pembayaran");
        jButtonPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPembayaranMouseClicked(evt);
            }
        });
        jButtonPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPembayaranActionPerformed(evt);
            }
        });

        jButtonPelaporan.setText("Pelaporan");
        jButtonPelaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPelaporanMouseClicked(evt);
            }
        });
        jButtonPelaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPelaporanActionPerformed(evt);
            }
        });

        jButtonLogout1.setText("Logout");
        jButtonLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogout1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonKamarku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPelaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jButtonKamarku)
                .addGap(18, 18, 18)
                .addComponent(jButtonPembayaran)
                .addGap(18, 18, 18)
                .addComponent(jButtonPelaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jButtonLogout1)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal", "Masalah", "Tanggapan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 580, 340));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Riwayat Laporan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 20));

        jButtonKembaliPelaporan.setText("Kembali");
        jButtonKembaliPelaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKembaliPelaporanMouseClicked(evt);
            }
        });
        jButtonKembaliPelaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliPelaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKembaliPelaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\CIRA\\CODING\\LATIHAN\\Semester 4\\PBO\\PenyewaKosanKu\\src\\Assets\\white bg.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPembayaranActionPerformed

    private void jButtonPelaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPelaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPelaporanActionPerformed

    private void jButtonKembaliPelaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliPelaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKembaliPelaporanActionPerformed

    private void jButtonKembaliPelaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliPelaporanMouseClicked
        // TODO add your handling code here:
        new PelaporanPenyewa(this.idPenyewa, this.namaPenyewa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonKembaliPelaporanMouseClicked

    private void jButtonPelaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPelaporanMouseClicked
        // TODO add your handling code here:
        new PelaporanPenyewa(this.idPenyewa, this.namaPenyewa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPelaporanMouseClicked

    private void jButtonLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogout1MouseClicked
        // TODO add your handling code here:
        
    int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            UserSession.clearSession();
            new LoginPenyewa().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonLogout1MouseClicked

    private void jButtonKamarkuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKamarkuMouseClicked
        // TODO add your handling code here:
        new DashboardPenyewa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonKamarkuMouseClicked

    private void jButtonPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPembayaranMouseClicked
        // TODO add your handling code here:
        new PembayaranPenyewa(this.idPenyewa, this.namaPenyewa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPembayaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatLaporanPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatLaporanPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatLaporanPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatLaporanPenyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatLaporanPenyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKamarku;
    private javax.swing.JButton jButtonKembaliPelaporan;
    private javax.swing.JButton jButtonLogout1;
    private javax.swing.JButton jButtonPelaporan;
    private javax.swing.JButton jButtonPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
